// vue-portfolio/src/components/Awards.vue
<template>
  <section id="awards" ref="sectionRef" class="py-20 bg-lightNavy/30">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div 
        class="text-center mb-16"
        v-motion
        :initial="{ opacity: 0, y: 30 }"
        :visible="{ opacity: 1, y: 0 }"
        :transition="{ duration: 800 }"
      >
        <h2 class="section-title">Awards & Recognition</h2>
        <div class="w-24 h-1 bg-accent mx-auto mb-8"></div>
        <p class="text-lg text-lightSlate max-w-3xl mx-auto">
          Recognition for academic excellence and research contributions.
        </p>
      </div>

      <div 
        class="max-w-4xl mx-auto"
        v-motion
        :initial="{ opacity: 0, y: 30 }"
        :visible="{ opacity: 1, y: 0 }"
        :transition="{ duration: 800, delay: 200 }"
      >
        <div v-if="awards.length > 0" class="relative">
          <!-- Timeline line -->
          <div class="absolute left-8 top-0 bottom-0 w-0.5 bg-accent/30"></div>
          
          <div class="space-y-8">
            <div
              v-for="(award, index) in awards"
              :key="index"
              class="relative flex items-start"
              v-motion
              :initial="{ opacity: 0, x: -20 }"
              :visible="{ opacity: 1, x: 0 }"
              :transition="{ duration: 600, delay: index * 100 }"
            >
              <!-- Timeline dot -->
              <div class="absolute left-6 w-4 h-4 bg-accent rounded-full border-4 border-navy z-10"></div>
              
              <!-- Content -->
              <div class="ml-16 bg-lightNavy p-6 rounded-lg border border-lightestNavy hover:border-accent transition-all duration-300 group">
                <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
                  <div class="flex-1">
                    <h3 class="text-xl font-semibold text-white mb-2 group-hover:text-accent transition-colors duration-200">
                      {{ award.title }}
                    </h3>
                    <div v-if="award.year" class="text-accent font-medium mb-3">
                      {{ award.year }}
                    </div>
                    <p v-if="award.content" class="text-lightSlate group-hover:text-lightestSlate transition-colors duration-200">
                      {{ award.content }}
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div v-else class="text-center py-12">
          <div class="text-lightSlate text-lg">
            No awards available at the moment.
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script>
import { ref, onMounted } from 'vue'
import { getAllContent } from '../utils/markdown'

export default {
  name: 'Awards',
  setup() {
    const sectionRef = ref(null)
    const awards = ref([])

    onMounted(() => {
      awards.value = getAllContent('awards')
    })

    return {
      sectionRef,
      awards
    }
  }
}
</script>

// react-portfolio/components/Awards.jsx
import { motion } from 'framer-motion';
import { useInView } from '../hooks/useInView';
import { getAllContent } from '../lib/markdown';

const Awards = () => {
  const [ref, isInView] = useInView({ once: true, margin: "-100px" });
  const awards = getAllContent('awards');

  return (
    <section id="awards" ref={ref} className="py-20 bg-lightNavy/30">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: isInView ? 1 : 0, y: isInView ? 0 : 30 }}
          transition={{ duration: 0.8 }}
          className="text-center mb-16"
        >
          <h2 className="section-title">Awards & Recognition</h2>
          <div className="w-24 h-1 bg-accent mx-auto mb-8"></div>
          <p className="text-lg text-lightSlate max-w-3xl mx-auto">
            Recognition for academic excellence and research contributions.
          </p>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: isInView ? 1 : 0, y: isInView ? 0 : 30 }}
          transition={{ duration: 0.8, delay: 0.2 }}
          className="max-w-4xl mx-auto"
        >
          {awards.length > 0 ? (
            <div className="relative">
              {/* Timeline line */}
              <div className="absolute left-8 top-0 bottom-0 w-0.5 bg-accent/30"></div>
              
              <div className="space-y-8">
                {awards.map((award, index) => (
                  <motion.div
                    key={index}
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: isInView ? 1 : 0, x: isInView ? 0 : -20 }}
                    transition={{ duration: 0.6, delay: index * 0.1 }}
                    className="relative flex items-start"
                  >
                    {/* Timeline dot */}
                    <div className="absolute left-6 w-4 h-4 bg-accent rounded-full border-4 border-navy z-10"></div>
                    
                    {/* Content */}
                    <div className="ml-16 bg-lightNavy p-6 rounded-lg border border-lightestNavy hover:border-accent transition-all duration-300 group">
                      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
                        <div className="flex-1">
                          <h3 className="text-xl font-semibold text-white mb-2 group-hover:text-accent transition-colors duration-200">
                            {award.title}
                          </h3>
                          {award.year && (
                            <div className="text-accent font-medium mb-3">
                              {award.year}
                            </div>
                          )}
                          {award.content && (
                            <p className="text-lightSlate group-hover:text-lightestSlate transition-colors duration-200">
                              {award.content}
                            </p>
                          )}
                        </div>
                      </div>
                    </div>
                  </motion.div>
                ))}
              </div>
            </div>
          ) : (
            <div className="text-center py-12">
              <div className="text-lightSlate text-lg">
                No awards available at the moment.
              </div>
            </div>
          )}
        </motion.div>
      </div>
    </section>
  );
};

export default Awards;
