// react-portfolio/components/Contact.jsx
import { motion } from 'framer-motion';
import { useInView } from '../hooks/useInView';

const Contact = () => {
  const [ref, isInView] = useInView({ once: true, margin: "-100px" });

  const contactInfo = [
    {
      type: 'Email',
      value: 'karanmirakhor@gmail.com',
      href: 'mailto:karanmirakhor@gmail.com',
      icon: (
        <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 4.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
        </svg>
      )
    },
    {
      type: 'Google Scholar',
      value: 'View Profile',
      href: 'https://scholar.google.com/citations?user=wpeFm64AAAAJ&hl=en',
      icon: (
        <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 24 24">
          <path d="M5.242 13.769L0 9.5 12 0l12 9.5-5.242 4.269C17.548 11.249 14.978 9.5 12 9.5c-2.977 0-5.548 1.748-6.758 4.269zM12 10a7 7 0 1 0 0 14 7 7 0 0 0 0-14z"/>
        </svg>
      )
    },
    {
      type: 'GitHub',
      value: 'karan-13-hub',
      href: 'https://github.com/karan-13-hub',
      icon: (
        <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 24 24">
          <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/>
        </svg>
      )
    },
    {
      type: 'LinkedIn',
      value: 'Connect',
      href: 'https://www.linkedin.com/in/karan-mirakhor-b065b7142/',
      icon: (
        <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 24 24">
          <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/>
        </svg>
      )
    },
    {
      type: 'CV',
      value: 'Download',
      href: 'https://drive.google.com/file/d/1KMUiU1Ze_I2ZgC0N5dFkpX_ucFn5C_G5/view?usp=sharing',
      icon: (
        <svg className="w-6 h-6" fill="currentColor" viewBox="0 0 24 24">
          <path d="M14,2H6A2,2 0 0,0 4,4V20A2,2 0 0,0 6,22H18A2,2 0 0,0 20,20V8L14,2M18,20H6V4H13V9H18V20Z"/>
        </svg>
      )
    }
  ];

  return (
    <section id="contact" ref={ref} className="py-20">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: isInView ? 1 : 0, y: isInView ? 0 : 30 }}
          transition={{ duration: 0.8 }}
          className="text-center mb-16"
        >
          <h2 className="section-title">Get In Touch</h2>
          <div className="w-24 h-1 bg-accent mx-auto mb-8"></div>
          <p className="text-lg text-lightSlate max-w-3xl mx-auto">
            I'm always interested in discussing new research opportunities, collaborations, 
            and innovative projects in AI and robotics.
          </p>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: isInView ? 1 : 0, y: isInView ? 0 : 30 }}
          transition={{ duration: 0.8, delay: 0.2 }}
          className="max-w-4xl mx-auto"
        >
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {contactInfo.map((contact, index) => (
              <motion.a
                key={index}
                whileHover={{ 
                  scale: 1.05, 
                  y: -5,
                  transition: { duration: 0.2 }
                }}
                whileTap={{ scale: 0.95 }}
                href={contact.href}
                target="_blank"
                rel="noopener noreferrer"
                className="card group cursor-pointer text-center hover:border-accent transition-all duration-300"
              >
                <div className="flex flex-col items-center space-y-4">
                  <div className="text-accent group-hover:text-white transition-colors duration-200">
                    {contact.icon}
                  </div>
                  <div>
                    <h3 className="text-lg font-semibold text-white group-hover:text-accent transition-colors duration-200">
                      {contact.type}
                    </h3>
                    <p className="text-lightSlate group-hover:text-lightestSlate transition-colors duration-200">
                      {contact.value}
                    </p>
                  </div>
                </div>
              </motion.a>
            ))}
          </div>

          {/* Call to Action */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: isInView ? 1 : 0, y: isInView ? 0 : 20 }}
            transition={{ duration: 0.8, delay: 0.4 }}
            className="text-center mt-12"
          >
            <motion.a
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              href="mailto:karanmirakhor@gmail.com"
              className="btn-primary text-lg px-8 py-4"
            >
              Send me an email
            </motion.a>
          </motion.div>
        </motion.div>
      </div>
    </section>
  );
};

export default Contact;

// vue-portfolio/src/components/Contact.vue
<template>
  <section id="contact" ref="sectionRef" class="py-20">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div 
        class="text-center mb-16"
        v-motion
        :initial="{ opacity: 0, y: 30 }"
        :visible="{ opacity: 1, y: 0 }"
        :transition="{ duration: 800 }"
      >
        <h2 class="section-title">Get In Touch</h2>
        <div class="w-24 h-1 bg-accent mx-auto mb-8"></div>
        <p class="text-lg text-lightSlate max-w-3xl mx-auto">
          I'm always interested in discussing new research opportunities, collaborations, 
          and innovative projects in AI and robotics.
        </p>
      </div>

      <div 
        class="max-w-4xl mx-auto"
        v-motion
        :initial="{ opacity: 0, y: 30 }"
        :visible="{ opacity: 1, y: 0 }"
        :transition="{ duration: 800, delay: 200 }"
      >
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          <a
            v-for="(contact, index) in contactInfo"
            :key="index"
            :href="contact.href"
            target="_blank"
            rel="noopener noreferrer"
            class="card group cursor-pointer text-center hover:border-accent transition-all duration-300"
            v-motion
            :hover="{ 
              scale: 1.05, 
              y: -5,
              transition: { duration: 200 }
            }"
            :tap="{ scale: 0.95 }"
          >
            <div class="flex flex-col items-center space-y-4">
              <div class="text-accent group-hover:text-white transition-colors duration-200">
                <component :is="contact.icon" class="w-6 h-6" />
              </div>
              <div>
                <h3 class="text-lg font-semibold text-white group-hover:text-accent transition-colors duration-200">
                  {{ contact.type }}
                </h3>
                <p class="text-lightSlate group-hover:text-lightestSlate transition-colors duration-200">
                  {{ contact.value }}
                </p>
              </div>
            </div>
          </a>
        </div>

        <!-- Call to Action -->
        <div 
          class="text-center mt-12"
          v-motion
          :initial="{ opacity: 0, y: 20 }"
          :visible="{ opacity: 1, y: 0 }"
          :transition="{ duration: 800, delay: 400 }"
        >
          <a
            href="mailto:karanmirakhor@gmail.com"
            class="btn-primary text-lg px-8 py-4"
            v-motion
            :hover="{ scale: 1.05 }"
            :tap="{ scale: 0.95 }"
          >
            Send me an email
          </a>
        </div>
      </div>
    </div>
  </section>
</template>

<script>
import { ref } from 'vue'

export default {
  name: 'Contact',
  setup() {
    const sectionRef = ref(null)

    const contactInfo = [
      {
        type: 'Email',
        value: 'karanmirakhor@gmail.com',
        href: 'mailto:karanmirakhor@gmail.com',
        icon: 'svg'
      },
      {
        type: 'Google Scholar',
        value: 'View Profile',
        href: 'https://scholar.google.com/citations?user=wpeFm64AAAAJ&hl=en',
        icon: 'svg'
      },
      {
        type: 'GitHub',
        value: 'karan-13-hub',
        href: 'https://github.com/karan-13-hub',
        icon: 'svg'
      },
      {
        type: 'LinkedIn',
        value: 'Connect',
        href: 'https://www.linkedin.com/in/karan-mirakhor-b065b7142/',
        icon: 'svg'
      },
      {
        type: 'CV',
        value: 'Download',
        href: 'https://drive.google.com/file/d/1KMUiU1Ze_I2ZgC0N5dFkpX_ucFn5C_G5/view?usp=sharing',
        icon: 'svg'
      }
    ]

    return {
      sectionRef,
      contactInfo
    }
  }
}
</script>
